# Welcome to Jekyll!

# Website settings
title: "fromtriptotrip"
description: "Andrey's blog, use Jekyll and github pages."
keywords: "Andrey, fromtriptotrip, blog, Jekyll, github, gh-pages"
baseurl: "/"
url: "http://www.fromtriptotrip.ru"

# author
author:
  name: 'adnaumov'
  first_name: 'Andrey'
  last_name: 'Naumov'
  email: 'mailto.anaumov@gmail.com'
  linkedin_username: 'adnaumov'
  vk_username: 'adnaumov'
  facebook_username: 'adnaumov'
  github_username: 'adnaumov'
  head_img: 'static/img/landing/adnaumov.jpg'
  desc: 'Information security specialist & Postgraduate student | Senior software developer | Saint Petersburg, Russia'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'ru'
    flag: 'static/img/flags/Russia.png'
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'http://www.fromtriptotrip.ru/static/img/blog'

# comment
disqus:
  name: fromtriptotrip
  public_key: HZqSzoj8IHkSBXDatnO3WXlQEcvHlN1AI1CfDuLiaj2znqSEufF07QItK1wrTvyZ

# google analytics
ga:
  id: UA-84973407-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
